language: node_js
sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '7'
  - '6'
before_install:
  - npm install -g polymer-cli
script:
  - xvfb-run npm test
